//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentEmail.ConsoleClient.SendEmailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendEmailService.ISendEmail")]
    public interface ISendEmail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendEmail/Send", ReplyAction="http://tempuri.org/ISendEmail/SendResponse")]
        void Send(string emailFrom, string password, string emailTo, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendEmail/Send", ReplyAction="http://tempuri.org/ISendEmail/SendResponse")]
        System.Threading.Tasks.Task SendAsync(string emailFrom, string password, string emailTo, string subject, string body);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISendEmailChannel : SentEmail.ConsoleClient.SendEmailService.ISendEmail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendEmailClient : System.ServiceModel.ClientBase<SentEmail.ConsoleClient.SendEmailService.ISendEmail>, SentEmail.ConsoleClient.SendEmailService.ISendEmail {
        
        public SendEmailClient() {
        }
        
        public SendEmailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendEmailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendEmailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendEmailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Send(string emailFrom, string password, string emailTo, string subject, string body) {
            base.Channel.Send(emailFrom, password, emailTo, subject, body);
        }
        
        public System.Threading.Tasks.Task SendAsync(string emailFrom, string password, string emailTo, string subject, string body) {
            return base.Channel.SendAsync(emailFrom, password, emailTo, subject, body);
        }
    }
}
